apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: postgresdatabases.database.idplatformkit.io
spec:
  group: database.idplatformkit.io
  scope: Namespaced
  names:
    kind: PostgresDatabase
    plural: postgresdatabases
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                writeConnectionSecretToRef:
                  type: object
                  description: >-
                    Name of the Secret (in this namespace) to write the
                    database connection details (host, port, dbname,
                    username, password) to.
                  properties:
                    name:
                      type: string
                  required:
                    - name
              required:
                - writeConnectionSecretToRef
